### ISSUE TITLE
ni_lib_veristand_custom_device_import_and_export_tool-1.0.0.11.vip is built incorrectly

### ISSUE THREAD

**Issue by rtzoeller** [NIVeriStandAdd-Ons/VeriStand-Addon-CD-Import-and-Export-Tool#11]
`ImportExport.lvlib` in the repository lists the dependency 

```
<Item Name="Pre-Import Action.vit" Type="VI" URL="../Pre-Import Action.vit"/>
```

but the version included in `ni_lib_veristand_custom_device_import_and_export_tool-1.0.0.11.vip` lists 

```
<Item Name="Pre-Import Action.vit" Type="VI" URL="../../../../../../../../../../../../Addons/Import Export/.Source/Pre-Import Action.vit"/>
```

---

This is causing the Routing and Faulting scripting API to fail to build; it attempts to pull in the entire lvlib as a dependency, but the lvlib claims to be missing `Pre-Import Action.vit`.

**Comment by rtzoeller** [comment]
@Karl-G1 is preparing a fix.

**Comment by czokubik** [comment]
I tested out bug fix committed by @Karl-G1. No errors, works fine.
